### PR TITLE
Replaces operating system unzip with node unzip and adds customisable build dir.

### PR DESCRIPTION
**Pull request by itsluke**

### CODE REVIEW

**Comment by alexspeller** [comment]
I'm suddenly hitting an issue with the zip file downloaded being corrupted - I'm wondering if you made this PR because you saw a similar issue of corrupted zip file or is it unrelated? Just trying to track down a very weird issue I'm seeing

**Comment by itsluke** [comment]
@alexspeller not exactly but I did encounter something similar due to the zip being streamed and it not completing before it tried to unzip, which would lead to it being corrupted.

**Comment by alexspeller** [comment]
It was [this](https://github.com/tomdale/fastboot-s3-notifier/pull/5) in the end

**Comment by tomdale** [comment]
@itsluke In my testing last year, `adm-zip` was quite a bit slower. Ideally folks who need a pure JS zip implementation can subclass and override the `unzipApp()` (which is one of the reasons I broke out each step into a separate method). I'd prefer to keep the current implementation but if it's not easy to swap in your own zip implementation I'd be happy to take PRs that make it easier.

**Pull request closed without merging**
