### PR TITLE
Add ability to set the AWS key id and secret

### PR DESCRIPTION
**Pull request by egjiri**
@tomdale can you take a look at this?

### CODE REVIEW

**Comment by tomdale** [comment]
@egjiri Can you say more about your use case? Is there any reason you aren't able to use the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables?

**Comment by egjiri** [comment]
@tomdale We are hosted through a company that fully manages the servers for us so we do not have any control to makes changes ourselves.

So, to answer your question, we can use the environment variables but it has to go through a support ticket which takes awhile as opposed to us just being able to set them ourselves.

Let me know if you think this doesn't provide enough value and I can close the PR

**Comment by tomdale** [comment]
@egjiri Nah it seems fine to include it, thank you for the PR. :)

**Comment by tomdale** [comment]
Released `fastboot-s3-downloader@0.2.2`.

**Comment by egjiri** [comment]
Thanks, I also just created a similar PR for the fastboot-s3-notifier https://github.com/tomdale/fastboot-s3-notifier/pull/7

**Pull request merged**
