### PR TITLE
Do not log into output to prevent max buffer size error

### PR DESCRIPTION
**Pull request by bobisjan**

### CODE REVIEW

**Comment by simonihmig** [comment]
I ran into the same issue just recently, and tried your changes, which indeed fix the issue! 👍

**Comment by bobisjan** [comment]
@kratiahuja, does this approach make sense? I would like to get rid of the custom fork we are using. Thanks

**Comment by kratiahuja** [comment]
I haven't worked much in this repository so I can't really intelligently review the impact of this. @rwjblue are you ok with this PR?

**Comment by rwjblue** [comment]
Ya, seems good to me!

**Comment by simonihmig** [comment]
> I would like to get rid of the custom fork we are using

Same! A release with this (still only on master) would be appreciated! 🙏

**Pull request merged**
