### PR TITLE
Allow to set AWS region

### PR DESCRIPTION
**Pull request by bobisjan**

### CODE REVIEW

**Comment by bobisjan** [comment]
👀 @tomdale

**Comment by simonihmig** [comment]
Btw, also had the problem that I wanted to use a S3 bucket from another region. However #6 was all that I needed to make it work!?

**Comment by bobisjan** [comment]
Changing signature version in #6 should work well. I would still prefer to allow to set region by user, if I know where the bucket lives, to remove roundtrip through the default (`us-east-1`) region.

**Comment by simonihmig** [comment]
Ah, I see, makes sense! 👍

**Comment by bobisjan** [comment]
@tomdale, resolved conflicts, ready to review ☺️.

**Comment by tomdale** [comment]
Thank you!

**Pull request merged**
